### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by svilenvul** [MusalaSoft/atmosphere-commons#3]
I followed the instructions in README.md, and tried to build the project. The build failed:

> C:\prj\openHAB\EclipseIDE\git\atmosphere-commons>gradlew build
> Downloading https://services.gradle.org/distributions/gradle-2.13-bin.zip
> 
> Unzipping C:\Users\svilen.valkanov.gradle\wrapper\dists\gradle-2.13-bin\4xsgxlfjcxvrea7akf941nvc7\gradle-2.13-bin.zip to C:\Users\svilen.valkanov.gradle\wrapp
> er\dists\gradle-2.13-bin\4xsgxlfjcxvrea7akf941nvc7
> :compileJava
> Download https://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.pom
> Download https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.pom
> Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/33/commons-parent-33.pom
> 
> FAILURE: Build failed with an exception.
> 
>  What went wrong:
> Could not resolve all dependencies for configuration ':compileClasspath'.
>  Could not find android:android:4.4.2_r4.
>   Searched in the following locations:
>       https://repo1.maven.org/maven2/android/android/4.4.2_r4/android-4.4.2_r4.pom
>       https://repo1.maven.org/maven2/android/android/4.4.2_r4/android-4.4.2_r4.jar
>       file:/C:/Users/svilen.valkanov/.m2/repository/android/android/4.4.2_r4/android-4.4.2_r4.pom
>       file:/C:/Users/svilen.valkanov/.m2/repository/android/android/4.4.2_r4/android-4.4.2_r4.jar
>   Required by:
>       :atmosphere-commons:0.0.1
> 
>  Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 4 mins 53.109 secs

I have attached file with debug info.

[build-failure-debug.txt](https://github.com/MusalaSoft/atmosphere-commons/files/347767/build-failure-debug.txt)

**Comment by svilenvul** [comment]
Thanks, I have installed the Android SDK, but I guess that I can not build the project with java 1.8:

> C:\Users\{user}\Downloads\atmosphere-commons>gradlew build
> :compileJava
> Download https://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar
> Download https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
> :compileJava FAILED
> 
> FAILURE: Build failed with an exception.
> 
>  What went wrong:
> Execution failed for task ':compileJava'.
>  Could not find tools.jar. Please check that C:\Program Files\Java\jdk1.8.0_65 contains a valid JDK installation.
> 
>  Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 19.196 secs

**Comment by vanogrid** [comment]
We currently use Java 8, so the project should be able to build, but unfortunately I can't reproduce this error. Could you check if you have JAVA_HOME set as an environment variable?

**Comment by svilenvul** [comment]
JAVA_HOME is set as system variable and is pointing to C:\Program Files\Java\jdk1.8.0_65

**Comment by dakatapetrov** [comment]
Check out [this link](http://stackoverflow.com/a/11345708).

The system property  `java.home` and the `JAVA_HOME` environment variable may differ.

Hope this helps :)
